sudo: true

language: php

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.1
  - nightly
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

env:
  matrix:
    - DEPENDENCIES=""
    - DEPENDENCIES="--prefer-lowest --prefer-stable"

before_script:
  - composer update --no-interaction --prefer-source $DEPENDENCIES

script:
  - ./vendor/bin/phpunit -d zend.enable_gc=0 --coverage-clover ./clover.xml
  - ./vendor/bin/phpcs --standard=PSR2 ./src/ ./tests/

after_script:
  - if [ $TRAVIS_PHP_VERSION != 'hhvm' ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [ $TRAVIS_PHP_VERSION != 'hhvm' ]; then php ocular.phar code-coverage:upload --format=php-clover ./clover.xml; fi

install:
  - echo "extension = amqp.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
